### ISSUE TITLE
Doesn't work with Safari

### ISSUE THREAD

**Issue by tmconnect** [Hube2/acf-medium-editor#13]
With Safari the behavior of the button bar doesn't work correctly. After the click on a button the button bar get closed and the format is not set to the text.

![safari_fail](https://cloud.githubusercontent.com/assets/2598781/22176417/2c6d61a0-e00a-11e6-90bb-25f194ef6cbd.gif)

If the button bar is gone and you do a single click in the text field, the button bar comes up.

After that if you double click text for selection, the button is already there on the second click.

I checked this on a clean setup with WP 4.7.1 (Twenty Seventeen) / ACF 5.5.5 and Medium Editor plugin are the only activated plugins.

**Comment by Hube2** [comment]
Thanks for letting me know, I'll look into this. I don't know if this has something to do with putting the toolbar inside of the ACF field container or it has to do with hiding and showing the button bar.

I can't really test on safari, would you be willing to do a quick test for me.  If you would comment out lines 105 to 110 of /assets/js/input.js. This is the part of the code that shows and hides the toolbar. See if that corrects the issue.

**Comment by Hube2** [comment]
Well, I'll be able to test on safari, but not for several days.

**Comment by Hube2** [comment]
Also, on line 61, remove display:none from the container styles. I am working on figuring out how to test this because I don't like having a plugin not working for some, but any help would be greatly appreciated.

~JH

**Comment by Hube2** [comment]
Found a way to test it, it has something to do with putting the toolbar in a relative container. I'm looking into the problem. I was hoping to use a relative container to make it look nice, but may need to abandon the idea.

**Comment by tmconnect** [comment]
The changes on `/assets/js/input.js` doesn't solve the problem...

**Comment by Hube2** [comment]
Can you please try the latest commit here and see if this corrects the problem. I have reverted to not using a relative container. I've also updated the Medium Editor script. It seems to be working to me.

**Comment by Hube2** [comment]
I'm still working on a solution to get this working the way I want it to work. I'm trying to figure out where the conflict is, debugging with a sledgehammer stripping the WP admin editor page of scripts one by one.

**Comment by Hube2** [comment]
I have narrowed this down to a conflict of some kind with ACF, which is just great.

**Comment by Hube2** [comment]
This page looks like hell, but if you look at it you see that it displays the same behavior. The only things loaded on this page are ACF, JQuery and the script for this plugin. I have tested without this plugin by instantiating medium editor in other ways and I get the same result.

I have narrowed it down to a conflict with medium editor and either jquery or acf and this conflict only happens in safari. I'm not exactly sure how to proceed at this point but I'm looking into it.

http://www.ssird5.com.php56-8.dfw3-2.websitetestlink.com/__test/medium-editor-2.php

**Comment by Hube2** [comment]
See the issue that I opened over on Medium Editor https://github.com/yabwe/medium-editor/issues/1283

~JH

**Comment by Hube2** [comment]
Even without using a relative container some of the buttons do not work in Safari. for example the italic button doesn't work correctly. It appears to be an issue with the tabindex still. I have attempted to remove the tabindex that appears to be causing this problem, but it doesn't seem to work. Let's hope that there's a positive response from medium editor.

**Comment by tmconnect** [comment]
The latest commit works for me on Safari.

Hope, that you'll find a solution the way you want it to work.

**Comment by Hube2** [comment]
In the newest update that I also pushed to wordpress.org repo, if the browser is safari then the toolbar is not put into a relative container. This should let it work in safari and if a fix is found for the medium editor problem then it'll be easy to change back. Until then this will have to do.

**Comment by JohanNyholm** [comment]
This bug seems to be present in MS Edge as well.

**Comment by Hube2** [comment]
I have completely removed the use of a relative container for medium editor in the current version due to browser incompatibilities in medium editor. @JohanNyholm are you seeing issues with the most recent version? If you are please provide more details.

**Comment by JohanNyholm** [comment]
@Hube2 Sounds great! Will have to try the latest version. I'll report back in case I encounter the error.
