### ISSUE TITLE
FYI on possible admin UI issue w/ field

### ISSUE THREAD

**Issue by lifeflowdan** [Hube2/acf-medium-editor#23]
Thanks for the plugin. Just to let you know, there appears to be some sort of compatibility issue between the ACF admin UI and the field. 

Situation: Existing Field Group, added Medium field, saved. 
Outcome: Field Group is frozen until plugin is deactivated. 

So, you can add the field to a field group, but then it will freeze it. I don't remember my field settings. 

I'm on ACF 5.7.0-RC3

**Comment by Hube2** [comment]
I don't understand what "Field Group is frozen" means.

Can you give me more information?

Are you seeing any PHP or JS errors?

**Comment by Hube2** [comment]
please see issue #9
