### ISSUE TITLE
Multiline - strange behaviour on init

### ISSUE THREAD

**Issue by marcwieland95** [Hube2/acf-medium-editor#29]
Hey. I really like your integration of Medium Editor into a ACF field.

When using it for a multiline text it doesn't work on the first return. On the second it starts to work as expected. I think this has something to do that it starts to create a textarea in the background.

![MediumEditor](https://user-images.githubusercontent.com/6168975/59765222-e1f59680-929d-11e9-9098-08f49e4c286b.gif)

**Comment by marcwieland95** [comment]
This just happens when the field was never stored with that type before.
After I saved once it's working as expected

**Comment by Hube2** [comment]
I'm not seeing this issue. Be sure to turn off both "disableReturn" and "disableDoubleReturn"

**Comment by marcwieland95** [comment]
Yeah. I guess it was "disableDoubleReturn"
